### Example from the task
POST http://localhost:8080/api/v1/format/human-readable
Content-Type: application/json

< assignment-example.json

### Empty list returns 'Closed' for all days

POST http://localhost:8080/api/v1/format/human-readable
Content-Type: application/json

{}

### Incomplete list works

POST http://localhost:8080/api/v1/format/human-readable
Content-Type: application/json

{
  "thursday": [
    {
      "type": "open",
      "value": 3600
    },
    {
      "type": "close",
      "value": 75600
    }
  ]
}
